=== pjimpin1207/LMSGI_UD4/Actividad3/esquema.dtd
<!ELEMENT concesionario (coche+)>
<!ELEMENT coche (codigo, marca, modelo, matricula, potencia, plazas, numero_puertas)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT matricula (#PCDATA)>
<!ELEMENT potencia (#PCDATA)>
<!ELEMENT plazas (#PCDATA)>
<!ELEMENT numero_puertas (#PCDATA)>

=== pjimpin1207/LMSGI_UD4/Actividad3/concesionario.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE concesionario SYSTEM "esquema.dtd">
<concesionario>
  <coche>
    <codigo>C001</codigo>
    <marca>Ford</marca>
    <modelo>Fiesta</modelo>
    <matricula>1234ABC</matricula>
    <potencia>75</potencia>
    <plazas>5</plazas>
    <numero_puertas>5</numero_puertas>
  </coche>
  <coche>
    <codigo>C002</codigo>
    <marca>Volkswagen</marca>
    <modelo>Polo</modelo>
    <matricula>5678XYZ</matricula>
    <potencia>90</potencia>
    <plazas>5</plazas>
    <numero_puertas>5</numero_puertas>
  </coche>
</concesionario>
