=== pjimpin1207/LMSGI_UD4/Actividad4/gestoria.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="gestoria">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="sede" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="codigo_sede" type="xs:string"/>
              <xs:element name="nombre_empleado" type="xs:string"/>
              <xs:element name="fecha_alta" type="xs:date"/>
              <xs:element name="cliente" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="codigo_cliente" type="xs:string"/>
                    <xs:element name="descripcion_cliente" minOccurs="0" type="xs:string"/>
                    <xs:element name="numero_viviendas" type="xs:int"/>
                    <xs:element name="coste_vivienda" type="xs:decimal"/>
                    <xs:element name="resumen_viviendas" type="xs:string"/>
                    <xs:element name="plazo_alta_hacienda" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== pjimpin1207/LMSGI_UD4/Actividad4/gestoria_XSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<gestoria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="gestoria gestoria.xsd">
        
  <sede>
    <codigo_sede>A1234567</codigo_sede>
    <nombre_empleado>Juan PÃ©rez</nombre_empleado>
    <fecha_alta>2024-12-01</fecha_alta>
    <cliente>
      <codigo_cliente>ABC-123</codigo_cliente>
      <descripcion_cliente>solvente</descripcion_cliente>
      <numero_viviendas>2</numero_viviendas>
      <coste_vivienda>150000.00</coste_vivienda>
      <resumen_viviendas>2 viviendas de 3 habitaciones</resumen_viviendas>
      <plazo_alta_hacienda>2024-12-02</plazo_alta_hacienda>
    </cliente>
  </sede>
</gestoria>
